---
title: Introduction
---

::: {note} Learning Outcomes
- Acquaint yourself with the overarching goals of Data 100.
- Understand the stages of the data science lifecycle.
- Build familiarity with `polars` and `polars` syntax.
- Learn a key data structure: `Series`.
:::

Data science is an interdisciplinary field with a variety of applications and offers great potential to address challenging societal issues. By building data science skills, you can empower yourself to participate in and drive conversations that shape your life and society as a whole, whether that be fighting against climate change, launching diversity initiatives, or more. 

The field of data science is rapidly evolving; many of the key technical underpinnings in modern-day data science have been popularized during the early 21^st^ century, and you will learn them throughout the course. It has a wide range of applications from science and medicine to sports. 

While data science has immense potential to address challenging problems facing society by enhancing our critical thinking, it can also be used obscure complex decisions and reinforce historical trends and biases. This course will implore you to consider the ethics of data science within its applications. 

Data science is fundamentally human-centered and facilitates decision-making by quantitatively balancing tradeoffs. To quantify things reliably, we must use and analyze data appropriately, apply critical thinking and skepticism at every step of the way, and consider how our decisions affect others.

Ultimately, data science is the application of data-centric, computational, and inferential thinking to:

- Understand the world (science).
- Solve problems (engineering).

```{image} images/venn.png
:alt: Venn Diagram illustrating that Data Science is the combination of hacking skills, math and statistics knowledgw, and substantive expertise.
:width: 450
```

A true mastery of data science requires a deep theoretical understanding and strong grasp of domain expertise. This course will help you build on the former -- specifically, the foundation of your technical knowledge, allowing you to take data and produce useful insights on the world's most challenging and ambiguous problems. 

::: {note} Course Goals
:class: dropdown
- Prepare you for advanced Berkeley courses in **data management, machine learning, and statistics.**
- Enable you to launch a career as a data scientist by providing experience working with **real-world data, tools, and techniques**.
- Empower you to apply computational and inferential thinking to address **real-world problems**.
:::

::: {note} Some Topics We'll Cover
:class: dropdown
- `polars` and `NumPy`
- Exploratory Data Analysis
- Regular Expressions
- Visualization
- Sampling
- Model Design and Loss Formulation
- Linear Regression
- Gradient Descent
- Logistic Regression
- Clustering 
- PCA
:::

::: {note} Prerequisites
:class: dropdown
To ensure that you can get the most out of the course content, please make sure that you are familiar with: 

- Using Python.
- Using Jupyter notebooks.
- Inference from Data 8.
- Linear algebra
:::

To set you up for success, we've organized concepts in Data 100 around the **data science lifecycle**: an *iterative* process that encompasses the various statistical and computational building blocks of data science. 

## Data Science Lifecycle

The data science lifecycle is a *high-level overview* of the data science workflow. It's a cycle of stages that a data scientist should explore as they conduct a thorough analysis of a data-driven problem. 

There are many variations of the data science lifecycle but the core ideas are all the same. In Data 100, we visualize the stages of the lifecycle using a flow diagram. Notice how there are two entry points. 

```{image} images/data_life_cycle.PNG
:alt: Data Science Lifecycle
:width: 500
```

### Ask a Question 

Whether by curiosity or necessity, data scientists constantly ask questions. For example, in the business world, data scientists may be interested in predicting the profit generated by a certain investment. In the field of medicine, they may ask whether some patients are more likely than others to benefit from a treatment. 

Posing questions is one of the primary ways the data science lifecycle begins. It helps to fully define the question. Here are some things you should ask yourself before framing a question.

- What problems are we trying to solve?
    - The goal of asking a question should be clear in order to justify your efforts to stakeholders.
- What are the hypotheses we want to test?
    - This gives a clear perspective from which to analyze final results.
- What are the metrics for our success?
    - This establishes a clear point to know when to conclude the project.

```{image} images/ask_question.PNG
:alt: Data Science Lifecycle: ask a question
:width: 500
```

### Obtain Data 

The second entry point to the lifecycle is by obtaining data. A careful analysis of any problem requires the use of data. Data may be readily available to us, or we may have to embark on a process to collect it. When doing so, it is crucial to ask the following:  

- What data do we have, and what data do we need?
    - Define the units of the data (people, cities, points in time, etc.) and what features to measure.
- How can we sample more data?
    - Scrape the web, collect manually, run experiments, etc.
- Is our data representative of the population we want to study?
    - If our data is not representative of our population of interest, then we can come to incorrect conclusions.
    
Key procedures: *data acquisition*, *data cleaning*

```{image} images/data_acquisition.PNG
:alt: Data science lifecycle: obtain data
:width: 500
```

### Understand the Data

Raw data itself is not inherently useful. It's impossible to discern all the patterns and relationships between variables without carefully investigating them. Therefore, translating pure data into actionable insights is a key job of a data scientist. For example, we may choose to ask:

- How is our data organized, and what does it contain?
    - Knowing what the data says about the world helps us better understand the world. 
- Do we have relevant data?
    - If the data we have collected is not useful to the question at hand, then we must collect more data.
- What are the biases, anomalies, or other issues with the data?
    - These can lead to many false conclusions if ignored, so data scientists must always be aware of these issues. 
- How do we transform the data to enable effective analysis?
    - Data is not always easy to interpret at first glance, so a data scientist should strive to reveal the hidden insights. 
    
Key procedures: *exploratory data analysis*, *data visualization*.

```{image} images/understand_data.PNG
:alt: Data science lifecycle: understand the data
:width: 500
```

### Understand the World

After observing the patterns in our data, we can begin answering our questions. This may require that we predict a quantity (machine learning) or measure the effect of some treatment (inference). 

From here, we may choose to report our results, or possibly conduct more analysis. We may not be satisfied with our findings, or our initial exploration may have brought up new questions that require new data.

- What does the data say about the world?
    - Given our models, the data will lead us to certain conclusions about the real world.   
- Does it answer our questions or accurately solve the problem?
    - If our model and data can not accomplish our goals, then we must reform our question, model, or both.  
- How robust are our conclusions and can we trust the predictions?
    - Inaccurate models can lead to false conclusions.

Key procedures: *model creation*, *prediction*, *inference*.

```{image} images/understand_world.PNG
:alt: Data science lifecycle: understand the world
:width: 500
```

The data science lifecycle is meant to be a set of general guidelines rather than a hard set of requirements. In our journey exploring the lifecycle, we'll cover both the underlying theory and technologies used in data science. By the end of the course, we hope that you start to see yourself as a data scientist.

With that, we'll begin by introducing one of the most important tools in exploratory data analysis: `polars`.

---

In this sequence of lectures, we will dive right into things by having you explore and manipulate real-world data. We'll first introduce `polars`, a popular Python library for interacting with **tabular data**.

## Tabular Data and `polars`

Data scientists work with data stored in a variety of formats. This class focuses primarily on *tabular data* — data that is stored in a table.

Tabular data is one of the most common systems that data scientists use to organize data. This is in large part due to the simplicity and flexibility of tables. Tables allow us to represent each **observation**, or instance of collecting data from an individual, as its own *row*. We can record each observation's distinct characteristics, or **features**, in separate *columns*.


To see this in action, we'll explore the `elections` dataset, which stores information about political candidates who ran for president of the United States in previous years.

In the `elections` dataset, each row (blue box) represents one instance of a candidate running for president in a particular year. For example, the first row represents Andrew Jackson running for president in the year 1824. Each column (yellow box) represents one characteristic piece of information about each presidential candidate. For example, the column named "Result" stores whether or not the candidate won the election. 

```{image} images/row_col.png
:alt: Dataframe with a row and a column highlighted
:width: 500
```

Your work in Data 8 helped you grow very familiar with using and interpreting data stored in a tabular format. Back then, you used the `Table` class of the `datascience` library, a special programming library created specifically for Data 8 students.

In Data 100, we will be working with the programming library `polars`, which is designed for manipulating tabular data quickly, even when the dataset is large. You will also come across `pandas`, the long-established standard for tabular data in Python and the inspiration for Petey, our panda bear mascot.

Using `polars`, we can

- Arrange data in a tabular format.
- Extract useful information filtered by specific conditions.
- Operate on data to gain new insights.
- Apply most `NumPy` functions to our data (our friends from Data 8) — though not the
  reductions. `np.mean(s)` raises where `s.mean()` works, because NumPy hands a reduction an
  `axis` argument that Polars does not take. `np.log`, `np.median` and `np.sort` are fine.
- Perform vectorized computations to speed up our analysis (Lab 1).

To begin our work in `polars`, we must first import the library into our Python environment. This will allow us to use `polars` data structures and methods in our code.

In [1]:
# `pl` is the conventional alias for Polars, as `np` is for NumPy
import polars as pl

There are two fundamental data structures in `polars`:

1. **`Series`**: 1D array data carrying a name and a single data type; best thought of as columnar data.
2. **`DataFrame`**: 2D tabular data with rows and columns.

`DataFrame`s and `Series` can be represented visually in the following diagram, which considers the first few rows of the `elections` dataset. It is drawn with `pandas`, so a few of its labels carry that library's vocabulary.

```{image} images/df_elections.png
:alt: The first five rows of the elections DataFrame, with its Result column drawn again to the right as a separate Series. A boxed column of the numbers 0 through 4 runs down the left-hand side of each, labeled 'Index of the elections DataFrame' and 'Index of the Result Series'. The Series is headed 'A Series named Result' and ends with the footer 'Name: Result, dtype: object'.
:width: 600
```

Notice how the **DataFrame** is a two-dimensional object — it contains both rows and columns. The **Series** above is a singular column of this `DataFrame`, namely the `Result` column.

The boxed column of numbers down the left-hand side is what `pandas` calls the **index**. `polars` stores no such column; instead, you reach a row by its **position**, counting from 0, which is how we will select values out of a `Series` shortly. The footer `dtype: object` is likewise the `pandas` name for text data, which `polars` calls `String`.

Today, we will start off from `Series` object.

## `Series`

A `Series` represents a column of a `DataFrame`; more generally, it can be any 1-dimensional array-like object. It contains both:

- A sequence of **values**, all of the same **data type**.
- A **name**, which becomes the column heading when the `Series` is placed in a `DataFrame`.

In the cell below, we create a `Series` and assign it to the variable `s`.

In [2]:
s = pl.Series(["welcome", "to", "data 100"])
s

shape: (3,)
Series: '' [str]
[
	"welcome"
	"to"
	"data 100"
]

<!-- tab-twins:begin bace57e2 -->
:::::{tab-set}
:::: {tab-item} Polars
:sync: pl
```python
s = pl.Series(["welcome", "to", "data 100"])
s
```

```text
shape: (3,)
Series: '' [str]
[
	"welcome"
	"to"
	"data 100"
]
```
::::

:::: {tab-item} pandas
:sync: pd
```python
s = pd.Series(["welcome", "to", "data 100"])
s
```

```text
0     welcome
1          to
2    data 100
dtype: object
```
::::
:::::
<!-- tab-twins:end -->

In [3]:
# Accessing data values within the Series
s.to_list()

['welcome', 'to', 'data 100']

In [4]:
# Accessing the name and data type of the Series
s.name, s.dtype

('', String)

<!-- tab-twins:begin 9371d026 -->
:::::{tab-set}
:::: {tab-item} Polars
:sync: pl
```python
# Accessing the name and data type of the Series
s.name, s.dtype
```

```text
('', String)
```
::::

:::: {tab-item} pandas
:sync: pd
```python
# Accessing the Index of the Series
s.index
```

```text
RangeIndex(start=0, stop=3, step=1)
```
::::
:::::
<!-- tab-twins:end -->

By default, a `Series` built from a list of values is unnamed, and its data type is inferred from the values it holds. Optionally, a name can be passed as the first argument to the constructor.

In [5]:
s = pl.Series("ratings", [-1, 10, 2])
s

shape: (3,)
Series: 'ratings' [i64]
[
	-1
	10
	2
]

In [6]:
s.name

'ratings'

The data type can also be changed after initialization. `.cast()` returns a new `Series`, so we assign the result back to `s`.

In [7]:
s = s.cast(pl.Float64)
s

shape: (3,)
Series: 'ratings' [f64]
[
	-1.0
	10.0
	2.0
]

In [8]:
s.dtype

Float64

#### Selection in `Series`

Much like when working with `NumPy` arrays, we can select a single value or a set of values from a `Series`. Elements are addressed by their **position** in the sequence, counting from 0. There are three primary methods:

1. A single position.
2. A list of positions.
3. A filtering condition.

To demonstrate this, let's define a new Series `s`.

In [9]:
s = pl.Series([4, -2, 0, 6])
s

shape: (4,)
Series: '' [i64]
[
	4
	-2
	0
	6
]

<!-- tab-twins:begin 168aebad -->
:::::{tab-set}
:::: {tab-item} Polars
:sync: pl
```python
s = pl.Series([4, -2, 0, 6])
s
```

```text
shape: (4,)
Series: '' [i64]
[
	4
	-2
	0
	6
]
```
::::

:::: {tab-item} pandas
:sync: pd
```python
s = pd.Series([4, -2, 0, 6], index = ["a", "b", "c", "d"])
s
```

```text
a    4
b   -2
c    0
d    6
dtype: int64
```
::::
:::::
<!-- tab-twins:end -->

##### A Single Position

In [10]:
# We return the value stored at position 0
s[0]

4

<!-- tab-twins:begin 120afc0f -->
:::::{tab-set}
:::: {tab-item} Polars
:sync: pl
```python
# We return the value stored at position 0
s[0]
```

```text
4
```
::::

:::: {tab-item} pandas
:sync: pd
```python
# We return the value stored at the index label "a"
s["a"]
```

```text
4
```
::::
:::::
<!-- tab-twins:end -->

##### A List of Positions

In [11]:
# We return a Series of the values stored at positions 0 and 2
s[[0, 2]]

shape: (2,)
Series: '' [i64]
[
	4
	0
]

<!-- tab-twins:begin 641029d4 -->
:::::{tab-set}
:::: {tab-item} Polars
:sync: pl
```python
# We return a Series of the values stored at positions 0 and 2
s[[0, 2]]
```

```text
shape: (2,)
Series: '' [i64]
[
	4
	0
]
```
::::

:::: {tab-item} pandas
:sync: pd
```python
# We return a Series of the values stored at the index labels "a" and "c"
s[["a", "c"]]
```

```text
a    4
c    0
dtype: int64
```
::::
:::::
<!-- tab-twins:end -->

##### A Filtering Condition

Perhaps the most interesting (and useful) method of selecting data from a `Series` is by using a filtering condition. 

First, we apply a boolean operation to the `Series`. This creates **a new `Series` of boolean values**.

In [12]:
# Filter condition: select all elements greater than 0
s > 0

shape: (4,)
Series: '' [bool]
[
	true
	false
	false
	true
]

We then pass this boolean condition to the `.filter()` method of our original `Series`. `polars` will keep only the entries that satisfy the condition.

In [13]:
s.filter(s > 0)

shape: (2,)
Series: '' [i64]
[
	4
	6
]

<!-- tab-twins:begin a53e4de1 -->
:::::{tab-set}
:::: {tab-item} Polars
:sync: pl
```python
s.filter(s > 0)
```

```text
shape: (2,)
Series: '' [i64]
[
	4
	6
]
```
::::

:::: {tab-item} pandas
:sync: pd
```python
s[s > 0]
```

```text
a    4
d    6
dtype: int64
```
::::
:::::
<!-- tab-twins:end -->